BaseURL=http://127.0.0.1:3000
BackendURL=mock
BrowserProjects=chromium,firefox,webkit,Microsoft Edge,Google Chrome,Mobile Chrome,Mobile Safari,Mobile Chrome Landscape,Mobile Safari Landscape,iPad Pro,Galaxy Tab S4,Chromium HiDPI,Firefox HiDPI,Chromium Reduced Motion,Chromium High Contrast,Chromium Slow 3G
Workers=8
ForbidOnly=false